[package]
name = "mobile-sdk-rs"
version = "0.1.0"
edition = "2021"
authors = ["Spruce Systems, Inc."]
license = "Apache-2.0 OR MIT"
description = "Mobile SDK Rust bindings"
repository = "https://github.com/spruceid/mobile-sdk-rs/"

[lib]
crate-type = ["staticlib", "lib", "cdylib"]
name = "mobile_sdk_rs"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
uniffi = { version = "0.27.1", features = ["cli"] }

isomdl = { git = "https://github.com/spruceid/isomdl", rev = "1f4f762" }

thiserror = "1.0.56"
hex = "0.4.3"
p256 = { version = "0.13.2", features = ["pkcs8"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_cbor = "0.11.2"
serde_json = "1.0.111"
uuid = { version = "1.6.1", features = ["v4"] }
w3c-vc-barcodes = { git = "https://github.com/spruceid/w3c-vc-barcodes", rev = "d3b3b9d" }
ssi = { git = "https://github.com/spruceid/ssi.git", rev = "88110a9", features = ["secp256r1", "secp384r1"] }
tracing = "0.1.40"

[dev-dependencies]
uniffi = { version = "0.27.1", features = ["bindgen-tests"] }
tokio = "1.39.2"
base64 = "0.22.0"

[build-dependencies]
uniffi = { version = "0.27.1", features = ["build"] }
