[package]
name = "mobile-sdk-rs"
version = "0.1.0"
edition = "2021"
authors = ["Spruce Systems, Inc."]
license = "Apache-2.0 OR MIT"
description = "Mobile SDK Rust bindings"
repository = "https://github.com/spruceid/mobile-sdk-rs/"

[lib]
crate-type = ["staticlib", "lib", "cdylib"]
name = "mobile_sdk_rs"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[features]
default = ["reqwest", "p256"]
reqwest = ["oid4vp/reqwest"]
p256 = ["oid4vp/p256"]

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.81"
did-jwk = "0.1.1"
hex = "0.4.3"
isomdl = "0.1.0"
oid4vp = { git = "https://github.com/spruceid/oid4vp-rs" }
p256 = { version = "0.13.2", features = ["pkcs8"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_cbor = "0.11.2"
serde_json = "1.0.111"
ssi-claims = "0.1.0"
ssi-dids = "0.2.0"
ssi-jwk = { version = "0.2.1", features = ["secp256r1"] }
ssi-vc = "0.3.0"
ssi-verification-methods = "0.1.1"
thiserror = "1.0.56"
tracing = "0.1.40"
uniffi = { version = "0.28.1", features = ["cli"] }
url = "2.5.2"
uuid = { version = "1.6.1", features = ["v4"] }


[dev-dependencies]
uniffi = { version = "0.28.1", features = ["bindgen-tests"] }

base64 = "0.22.0"

[build-dependencies]
uniffi = { version = "0.28.1", features = ["build"] }

[patch.crates-io]
isomdl = { git = "https://github.com/spruceid/isomdl", rev = "1f4f762" }

[patch.'https://github.com/spruceid/oid4vp-rs']
oid4vp = { path = "../oid4vp-rs" }
