// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(wallet_sdk_rsFFI)
import wallet_sdk_rsFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_wallet_sdk_rs_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_wallet_sdk_rs_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        // TODO: This copies the buffer. Can we read directly from a
        // Rust buffer?
        self.init(bytes: rustBuffer.data!, count: Int(rustBuffer.len))
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous go the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_PANIC: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: nil)
}

private func rustCallWithError<T>(
    _ errorHandler: @escaping (RustBuffer) throws -> Error,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_PANIC:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
                throw CancellationError()

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

// Public interface members begin here.


fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


public protocol MDocProtocol {
    func id()   -> Uuid
    
}

public class MDoc: MDocProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { uniffi_wallet_sdk_rs_fn_free_mdoc(pointer, $0) }
    }

    

    public static func fromCbor(value: Data) throws -> MDoc {
        return MDoc(unsafeFromRawPointer: try rustCallWithError(FfiConverterTypeMDocInitError.lift) {
    uniffi_wallet_sdk_rs_fn_constructor_mdoc_from_cbor(
        FfiConverterData.lower(value),$0)
})
    }

    

    
    

    public func id()  -> Uuid {
        return try!  FfiConverterTypeUuid.lift(
            try! 
    rustCall() {
    
    uniffi_wallet_sdk_rs_fn_method_mdoc_id(self.pointer, $0
    )
}
        )
    }
}

public struct FfiConverterTypeMDoc: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = MDoc

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MDoc {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: MDoc, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> MDoc {
        return MDoc(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: MDoc) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}


public func FfiConverterTypeMDoc_lift(_ pointer: UnsafeMutableRawPointer) throws -> MDoc {
    return try FfiConverterTypeMDoc.lift(pointer)
}

public func FfiConverterTypeMDoc_lower(_ value: MDoc) -> UnsafeMutableRawPointer {
    return FfiConverterTypeMDoc.lower(value)
}


public protocol SessionManagerProtocol {
    
}

public class SessionManager: SessionManagerProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { uniffi_wallet_sdk_rs_fn_free_sessionmanager(pointer, $0) }
    }

    

    
    
}

public struct FfiConverterTypeSessionManager: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = SessionManager

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionManager {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: SessionManager, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> SessionManager {
        return SessionManager(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: SessionManager) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}


public func FfiConverterTypeSessionManager_lift(_ pointer: UnsafeMutableRawPointer) throws -> SessionManager {
    return try FfiConverterTypeSessionManager.lift(pointer)
}

public func FfiConverterTypeSessionManager_lower(_ value: SessionManager) -> UnsafeMutableRawPointer {
    return FfiConverterTypeSessionManager.lower(value)
}


public struct ItemsRequest {
    public var docType: String
    public var namespaces: [String: [String: Bool]]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(docType: String, namespaces: [String: [String: Bool]]) {
        self.docType = docType
        self.namespaces = namespaces
    }
}


extension ItemsRequest: Equatable, Hashable {
    public static func ==(lhs: ItemsRequest, rhs: ItemsRequest) -> Bool {
        if lhs.docType != rhs.docType {
            return false
        }
        if lhs.namespaces != rhs.namespaces {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(docType)
        hasher.combine(namespaces)
    }
}


public struct FfiConverterTypeItemsRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ItemsRequest {
        return try ItemsRequest(
            docType: FfiConverterString.read(from: &buf), 
            namespaces: FfiConverterDictionaryStringDictionaryStringBool.read(from: &buf)
        )
    }

    public static func write(_ value: ItemsRequest, into buf: inout [UInt8]) {
        FfiConverterString.write(value.docType, into: &buf)
        FfiConverterDictionaryStringDictionaryStringBool.write(value.namespaces, into: &buf)
    }
}


public func FfiConverterTypeItemsRequest_lift(_ buf: RustBuffer) throws -> ItemsRequest {
    return try FfiConverterTypeItemsRequest.lift(buf)
}

public func FfiConverterTypeItemsRequest_lower(_ value: ItemsRequest) -> RustBuffer {
    return FfiConverterTypeItemsRequest.lower(value)
}


public struct RequestData {
    public var sessionManager: SessionManager
    public var itemsRequests: [ItemsRequest]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(sessionManager: SessionManager, itemsRequests: [ItemsRequest]) {
        self.sessionManager = sessionManager
        self.itemsRequests = itemsRequests
    }
}



public struct FfiConverterTypeRequestData: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RequestData {
        return try RequestData(
            sessionManager: FfiConverterTypeSessionManager.read(from: &buf), 
            itemsRequests: FfiConverterSequenceTypeItemsRequest.read(from: &buf)
        )
    }

    public static func write(_ value: RequestData, into buf: inout [UInt8]) {
        FfiConverterTypeSessionManager.write(value.sessionManager, into: &buf)
        FfiConverterSequenceTypeItemsRequest.write(value.itemsRequests, into: &buf)
    }
}


public func FfiConverterTypeRequestData_lift(_ buf: RustBuffer) throws -> RequestData {
    return try FfiConverterTypeRequestData.lift(buf)
}

public func FfiConverterTypeRequestData_lower(_ value: RequestData) -> RustBuffer {
    return FfiConverterTypeRequestData.lower(value)
}


public struct ResponseData {
    public var payload: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(payload: Data) {
        self.payload = payload
    }
}


extension ResponseData: Equatable, Hashable {
    public static func ==(lhs: ResponseData, rhs: ResponseData) -> Bool {
        if lhs.payload != rhs.payload {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(payload)
    }
}


public struct FfiConverterTypeResponseData: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ResponseData {
        return try ResponseData(
            payload: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: ResponseData, into buf: inout [UInt8]) {
        FfiConverterData.write(value.payload, into: &buf)
    }
}


public func FfiConverterTypeResponseData_lift(_ buf: RustBuffer) throws -> ResponseData {
    return try FfiConverterTypeResponseData.lift(buf)
}

public func FfiConverterTypeResponseData_lower(_ value: ResponseData) -> RustBuffer {
    return FfiConverterTypeResponseData.lower(value)
}


public struct SessionData {
    public var state: String
    public var qrCodeUri: String
    public var bleIdent: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(state: String, qrCodeUri: String, bleIdent: String) {
        self.state = state
        self.qrCodeUri = qrCodeUri
        self.bleIdent = bleIdent
    }
}


extension SessionData: Equatable, Hashable {
    public static func ==(lhs: SessionData, rhs: SessionData) -> Bool {
        if lhs.state != rhs.state {
            return false
        }
        if lhs.qrCodeUri != rhs.qrCodeUri {
            return false
        }
        if lhs.bleIdent != rhs.bleIdent {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(state)
        hasher.combine(qrCodeUri)
        hasher.combine(bleIdent)
    }
}


public struct FfiConverterTypeSessionData: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionData {
        return try SessionData(
            state: FfiConverterString.read(from: &buf), 
            qrCodeUri: FfiConverterString.read(from: &buf), 
            bleIdent: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SessionData, into buf: inout [UInt8]) {
        FfiConverterString.write(value.state, into: &buf)
        FfiConverterString.write(value.qrCodeUri, into: &buf)
        FfiConverterString.write(value.bleIdent, into: &buf)
    }
}


public func FfiConverterTypeSessionData_lift(_ buf: RustBuffer) throws -> SessionData {
    return try FfiConverterTypeSessionData.lift(buf)
}

public func FfiConverterTypeSessionData_lower(_ value: SessionData) -> RustBuffer {
    return FfiConverterTypeSessionData.lower(value)
}


public struct SignatureData {
    public var state: String
    public var response: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(state: String, response: Data) {
        self.state = state
        self.response = response
    }
}


extension SignatureData: Equatable, Hashable {
    public static func ==(lhs: SignatureData, rhs: SignatureData) -> Bool {
        if lhs.state != rhs.state {
            return false
        }
        if lhs.response != rhs.response {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(state)
        hasher.combine(response)
    }
}


public struct FfiConverterTypeSignatureData: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SignatureData {
        return try SignatureData(
            state: FfiConverterString.read(from: &buf), 
            response: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: SignatureData, into buf: inout [UInt8]) {
        FfiConverterString.write(value.state, into: &buf)
        FfiConverterData.write(value.response, into: &buf)
    }
}


public func FfiConverterTypeSignatureData_lift(_ buf: RustBuffer) throws -> SignatureData {
    return try FfiConverterTypeSignatureData.lift(buf)
}

public func FfiConverterTypeSignatureData_lower(_ value: SignatureData) -> RustBuffer {
    return FfiConverterTypeSignatureData.lower(value)
}

public enum MDocInitError {

    
    
    case Generic(value: String)

    fileprivate static func uniffiErrorHandler(_ error: RustBuffer) throws -> Error {
        return try FfiConverterTypeMDocInitError.lift(error)
    }
}


public struct FfiConverterTypeMDocInitError: FfiConverterRustBuffer {
    typealias SwiftType = MDocInitError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MDocInitError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Generic(
            value: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MDocInitError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Generic(value):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(value, into: &buf)
            
        }
    }
}


extension MDocInitError: Equatable, Hashable {}

extension MDocInitError: Error { }

public enum RequestError {

    
    
    case Generic(value: String)

    fileprivate static func uniffiErrorHandler(_ error: RustBuffer) throws -> Error {
        return try FfiConverterTypeRequestError.lift(error)
    }
}


public struct FfiConverterTypeRequestError: FfiConverterRustBuffer {
    typealias SwiftType = RequestError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RequestError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Generic(
            value: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RequestError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Generic(value):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(value, into: &buf)
            
        }
    }
}


extension RequestError: Equatable, Hashable {}

extension RequestError: Error { }

public enum ResponseError {

    
    
    case MissingSignature
    case Generic(value: String)

    fileprivate static func uniffiErrorHandler(_ error: RustBuffer) throws -> Error {
        return try FfiConverterTypeResponseError.lift(error)
    }
}


public struct FfiConverterTypeResponseError: FfiConverterRustBuffer {
    typealias SwiftType = ResponseError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ResponseError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .MissingSignature
        case 2: return .Generic(
            value: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ResponseError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .MissingSignature:
            writeInt(&buf, Int32(1))
        
        
        case let .Generic(value):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(value, into: &buf)
            
        }
    }
}


extension ResponseError: Equatable, Hashable {}

extension ResponseError: Error { }

public enum SessionError {

    
    
    case Generic(value: String)

    fileprivate static func uniffiErrorHandler(_ error: RustBuffer) throws -> Error {
        return try FfiConverterTypeSessionError.lift(error)
    }
}


public struct FfiConverterTypeSessionError: FfiConverterRustBuffer {
    typealias SwiftType = SessionError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Generic(
            value: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SessionError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Generic(value):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(value, into: &buf)
            
        }
    }
}


extension SessionError: Equatable, Hashable {}

extension SessionError: Error { }

public enum SignatureError {

    
    
    case TooManyDocuments
    case Generic(value: String)

    fileprivate static func uniffiErrorHandler(_ error: RustBuffer) throws -> Error {
        return try FfiConverterTypeSignatureError.lift(error)
    }
}


public struct FfiConverterTypeSignatureError: FfiConverterRustBuffer {
    typealias SwiftType = SignatureError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SignatureError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .TooManyDocuments
        case 2: return .Generic(
            value: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SignatureError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .TooManyDocuments:
            writeInt(&buf, Int32(1))
        
        
        case let .Generic(value):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(value, into: &buf)
            
        }
    }
}


extension SignatureError: Equatable, Hashable {}

extension SignatureError: Error { }

public enum TerminationError {

    
    
    case Generic(value: String)

    fileprivate static func uniffiErrorHandler(_ error: RustBuffer) throws -> Error {
        return try FfiConverterTypeTerminationError.lift(error)
    }
}


public struct FfiConverterTypeTerminationError: FfiConverterRustBuffer {
    typealias SwiftType = TerminationError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TerminationError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Generic(
            value: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TerminationError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Generic(value):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(value, into: &buf)
            
        }
    }
}


extension TerminationError: Equatable, Hashable {}

extension TerminationError: Error { }

fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

fileprivate struct FfiConverterSequenceTypeItemsRequest: FfiConverterRustBuffer {
    typealias SwiftType = [ItemsRequest]

    public static func write(_ value: [ItemsRequest], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeItemsRequest.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ItemsRequest] {
        let len: Int32 = try readInt(&buf)
        var seq = [ItemsRequest]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeItemsRequest.read(from: &buf))
        }
        return seq
    }
}

fileprivate struct FfiConverterDictionaryStringBool: FfiConverterRustBuffer {
    public static func write(_ value: [String: Bool], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterBool.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: Bool] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: Bool]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterBool.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}

fileprivate struct FfiConverterDictionaryStringSequenceString: FfiConverterRustBuffer {
    public static func write(_ value: [String: [String]], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterSequenceString.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: [String]] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: [String]]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterSequenceString.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}

fileprivate struct FfiConverterDictionaryStringDictionaryStringBool: FfiConverterRustBuffer {
    public static func write(_ value: [String: [String: Bool]], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterDictionaryStringBool.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: [String: Bool]] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: [String: Bool]]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterDictionaryStringBool.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}

fileprivate struct FfiConverterDictionaryStringDictionaryStringSequenceString: FfiConverterRustBuffer {
    public static func write(_ value: [String: [String: [String]]], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterDictionaryStringSequenceString.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: [String: [String]]] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: [String: [String]]]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterDictionaryStringSequenceString.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}


/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias Uuid = String
public struct FfiConverterTypeUuid: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Uuid {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: Uuid, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> Uuid {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: Uuid) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


public func FfiConverterTypeUuid_lift(_ value: RustBuffer) throws -> Uuid {
    return try FfiConverterTypeUuid.lift(value)
}

public func FfiConverterTypeUuid_lower(_ value: Uuid) -> RustBuffer {
    return FfiConverterTypeUuid.lower(value)
}


public func handleRequest(state: String, request: Data) throws -> RequestData {
    return try  FfiConverterTypeRequestData.lift(
        try rustCallWithError(FfiConverterTypeRequestError.lift) {
    uniffi_wallet_sdk_rs_fn_func_handle_request(
        FfiConverterString.lower(state),
        FfiConverterData.lower(request),$0)
}
    )
}

public func helloFfi()  -> String {
    return try!  FfiConverterString.lift(
        try! rustCall() {
    uniffi_wallet_sdk_rs_fn_func_hello_ffi($0)
}
    )
}

public func initialiseSession(document: MDoc, uuid: Uuid) throws -> SessionData {
    return try  FfiConverterTypeSessionData.lift(
        try rustCallWithError(FfiConverterTypeSessionError.lift) {
    uniffi_wallet_sdk_rs_fn_func_initialise_session(
        FfiConverterTypeMDoc.lower(document),
        FfiConverterTypeUuid.lower(uuid),$0)
}
    )
}

public func submitResponse(sessionManager: SessionManager, itemsRequests: [ItemsRequest], permittedItems: [String: [String: [String]]]) throws -> ResponseData {
    return try  FfiConverterTypeResponseData.lift(
        try rustCallWithError(FfiConverterTypeResponseError.lift) {
    uniffi_wallet_sdk_rs_fn_func_submit_response(
        FfiConverterTypeSessionManager.lower(sessionManager),
        FfiConverterSequenceTypeItemsRequest.lower(itemsRequests),
        FfiConverterDictionaryStringDictionaryStringSequenceString.lower(permittedItems),$0)
}
    )
}

public func submitSignature(sessionManager: SessionManager, signature: Data) throws -> SignatureData {
    return try  FfiConverterTypeSignatureData.lift(
        try rustCallWithError(FfiConverterTypeSignatureError.lift) {
    uniffi_wallet_sdk_rs_fn_func_submit_signature(
        FfiConverterTypeSessionManager.lower(sessionManager),
        FfiConverterData.lower(signature),$0)
}
    )
}

public func terminateSession() throws -> Data {
    return try  FfiConverterData.lift(
        try rustCallWithError(FfiConverterTypeTerminationError.lift) {
    uniffi_wallet_sdk_rs_fn_func_terminate_session($0)
}
    )
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variables to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 24
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_wallet_sdk_rs_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_wallet_sdk_rs_checksum_func_handle_request() != 8171) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wallet_sdk_rs_checksum_func_hello_ffi() != 49556) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wallet_sdk_rs_checksum_func_initialise_session() != 41897) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wallet_sdk_rs_checksum_func_submit_response() != 45596) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wallet_sdk_rs_checksum_func_submit_signature() != 58193) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wallet_sdk_rs_checksum_func_terminate_session() != 35293) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wallet_sdk_rs_checksum_method_mdoc_id() != 56888) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wallet_sdk_rs_checksum_constructor_mdoc_from_cbor() != 23024) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}