name: cd

on:
  push:
    tags:
      - v*
    branches: [ "wall-92-cd-for-uniffi" ]

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kotlin
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Publish package
      uses: gradle/gradle-build-action@v2
      with:
        arguments: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
